apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: fcclab
      defaultBucket: fcclab
      tlsSkipVerify: true
    secureJsonData:
      token: fcclab_token
    isDefault: true
    editable: false
